name: company_project
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter






  cupertino_icons: ^1.0.6
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.2
  firebase_storage: ^11.7.4
  google_fonts: ^6.2.1

  badges: ^3.1.2
  carousel_slider: ^4.2.1
  image_picker: ^1.1.0
  flutter_stripe: ^10.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true


  assets:
      - assets/images/


